package online_registration;

public class Course {
	private int courseId;
	private String title;
	private String description;
	private int credits;

	// Constructor for creating a new course (courseId is auto-generated by MySQL)
	public Course(String title, String description, int credits) {
		this.title = title;
		this.description = description;
		this.credits = credits;
	}

	// Constructor for retrieving an existing course from the database
	public Course(int courseId, String title, String description, int credits) {
		this.courseId = courseId;
		this.title = title;
		this.description = description;
		this.credits = credits;
	}

	/**
	 * Overloaded Constructor to support TestNG setup strings smoothly.
	 */
	public Course(String testCourseCode, String title) {
		try {
		if (testCourseCode != null) {
		this.courseId = Integer.parseInt(testCourseCode.replaceAll("[^0-9]", ""));
		}
		} catch (NumberFormatException e) {
		this.courseId = testCourseCode != null ? testCourseCode.hashCode() : 0;
		}
		this.title = title;
		this.credits = 3;
	}

	// Getters and Setters
	public int getCourseId() { return courseId; }
	public void setCourseId(int courseId) { this.courseId = courseId; }

	public String getTitle() { return title; }
	public void setTitle(String title) { this.title = title; }

	public String getDescription() { return description; }
	public void setDescription(String description) { this.description = description; }

	public int getCredits() { return credits; }
	public void setCredits(int credits) { this.credits = credits; }
}