package online_registration;

public class Student {
	private int studentId;
	private String firstName;
	private String lastName;
	private String email;
	private Integer majorId; // Using Integer wrapper because major_id can be NULL

	/**
	 * DOCKING CONSTRUCTOR FOR TESTNG SETUPS.
	 * Maps test inputs securely while ensuring robust, graceful string cleaning.
	 */
	public Student(String dummyId, String firstName, String lastName, boolean isTestContext) {
		try {
		if (dummyId != null) {
		this.studentId = Integer.parseInt(dummyId.replaceAll("[^0-9]", ""));
		}
		} catch (NumberFormatException e) {
		this.studentId = dummyId != null ? dummyId.hashCode() : 0;
		}
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = "test@umgc.edu";
		this.majorId = null;
	}

	// Constructor for creating a new student (ID auto-generated by MySQL)
	public Student(String firstName, String lastName, String email, Integer majorId) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.majorId = majorId;
	}

	// Constructor for retrieving an existing student from the database
	public Student(int studentId, String firstName, String lastName, String email, Integer majorId) {
		this.studentId = studentId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.majorId = majorId;
	}

	/**
	 * Alias getter to handle ID calls cleanly from the controller as a String.
	 */
	public String getStudentID() {
		return String.valueOf(this.studentId);
	}

	// Getters and Setters
	public int getStudentId() { return studentId; }
	public void setStudentId(int studentId) { this.studentId = studentId; }

	public String getFirstName() { return firstName; }
	public void setFirstName(String firstName) { this.firstName = firstName; }

	public String getLastName() { return lastName; }
	public void setLastName(String lastName) { this.lastName = lastName; }

	public String getEmail() { return email; }
	public void setEmail(String email) { this.email = email; }

	public Integer getMajorId() { return majorId; }
	public void setMajorId(Integer majorId) { this.majorId = majorId; }
}